name: Ion
version: 1.0.0
main: net.starlegacy.StarLegacy
depend: [ LuckPerms, Vault, dynmap, WorldEdit, Citizens, WorldGuard ]
softdepend: [ GriefDefender ]
authors: [ PeterCrawley, trainb0y, Sciath, MicleBrick ]
api-version: "1.17"
