name: StarLegacy
version: VersionsTakeEffort
main: net.starlegacy.StarLegacy
loadbefore: [ Essentials ]
depend: [ LuckPerms, Vault, dynmap, WorldEdit, Citizens, WorldGuard ]
softdepend: [ GameAPI, GriefDefender ]
api-version: "1.16"
